threshold: 10
audio_path: "make_1st_1cr/How to make YOUR FIRST 1CR (in 2024)  Sharing Practical Experiences  Akshat Shrivastava.mp4"
srt_path: "make_1st_1cr/How to make YOUR FIRST 1CR (in 2024) | Sharing Practical Experiences | Akshat Shrivastava_English (India).srt"
output_path: "make_1st_1cr/test/"
